
version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  ingestion:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.10.18
    depends_on:
      qdrant:
        condition: service_started
    command: ["python3", "-m", "ingest.ingest_data_prefect"]
    environment:
      - QDRANT_URL=http://qdrant:6333
