version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fashion_assistant
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    depends_on:
      qdrant:
        condition: service_started

  ingestion:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.10.18
    depends_on:
      qdrant:
        condition: service_started
      postgres:
        condition: service_started
    command: ["python3", "-m", "ingest.ingest_data_prefect"]
    environment:
      - QDRANT_URL=http://qdrant:6333
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fashion_assistant

  flask-app:
    build:
      context: .
      args:
        PYTHON_VERSION: 3.10.18
    depends_on:
      ingestion:
        condition: service_completed_successfully
      qdrant:
        condition: service_started
      postgres:
        condition: service_started
    ports:
      - "5001:5001"
    command: ["sh", "-c", "python3 -c 'from api.db import init_db; init_db()' && flask run --host=0.0.0.0 --port=5001"]
    environment:
      - FLASK_APP=api.app
      - QDRANT_URL=http://qdrant:6333
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fashion_assistant